name: e2e Test

on:
  push:
    paths:
      - 'packages/e2e/**'
      - '.github/workflows/e2e-test.yml'

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for Vercel deployment
        uses: mskelton/wait-for-vercel-action@v1
        id: wait-for-vercel
        with:
          prod-url: tigtuki.mayer.pub
          token: ${{ secrets.VERCEL_TOKEN }}
          await-build: true

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          working-directory: packages/e2e
          record: true
        env:
          CYPRESS_BASE_URL: ${{ steps.wait-for-vercel.outputs.url }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
